# Config
# https://github.com/caksoylar/zmk-rgbled-widget#kconfig-reference
CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_BATTERY_STATUS=y
CONFIG_RGBLED_WIDGET_CONN_STATUS=y

# Battery Widget
CONFIG_RGBLED_WIDGET_BATTERY_SHOW_ONLY_PERIPHERALS=y
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=80
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_LOW=20

# Baterry Colors
CONFIG_RGBLED_WIDGET_COLOR_HIGH=2
CONFIG_RGBLED_WIDGET_COLOR_MEDIUM=3
CONFIG_RGBLED_WIDGET_COLOR_LOW=1
